language: kotlin
jdk:
  - oraclejdk8
before_script:
  - chmod +x gradlew
script:
  - ./gradlew --version
  - ./gradlew check
  - ./gradlew jacocoTestReport
after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)