language: java
jdk:
  - oraclejdk8
before_script:
  - chmod +x gradlew
install:
  - pip install --upgrade pip
  - pip install codecov
script:
  - ./gradlew --version
  - ./gradlew check
  - ./gradlew jacocoTestReport
after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)